name: Generate Roadmap
on:
  workflow_dispatch:
jobs:
  roadmap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: inat-get/action-is-roadmap@main
        name: Generate Roadmap
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_type: wiki
          wiki_title: Roadmap
